version: '3.8'

services:
  redis-uf:
    image: redis:7.2.4
    container_name: redis-uf
    ports:
      - "6379:6379"
    networks:
      - uf-network
    volumes:
      - redis-uf-data:/data

networks:
  uf-network:
    driver: bridge

volumes:
  redis-uf-data:
    driver: local
